name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.17.4
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  bottom_picker: ^2.7.0
  timeago: ^3.1.0
  page_transition: ^2.1.0
  get: ^4.6.6
  http: ^0.13.3
  photo_view: ^0.14.0
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  image_picker: ^1.1.2
  emailjs: ^1.1.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  dotted_border: ^2.1.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_signin_button: ^2.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Include your image assets here
  assets:
    - assets/image/logo_edulocal.png
    - assets/image/image2.png
    - assets/image/Login.png
    - assets/image/google.png
    - assets/image/newcourse.png
    - assets/image/profile.png
    - assets/image/english.png
    - assets/image/programming.png
    - assets/image/Vector.png
    - assets/image/adminprofile.png
    - assets/image/confirm.png
    - assets/image/deleterole.png
    - assets/image/sendnotif.png
    


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/poppins/Poppins-Black.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


